"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from kombu import Queue

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

load_dotenv(BASE_DIR.parent / ".env")


# Application definition

INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "drf_spectacular",
    "channels",
    "djoser",
    "rest_framework_simplejwt.token_blacklist",
    # Local
    "accounts",
    "api",
    "tournaments",
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "accounts.middleware.SessionActivityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": ("django.contrib.auth.password_validation.MinimumLengthValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation.CommonPasswordValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation.NumericPasswordValidator"),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "noreply@dice-tournament.local",
)

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}

DJOSER = {
    "PASSWORD_RESET_CONFIRM_URL": "set-password/?uid={uid}&token={token}",
    "PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND": False,
    "TOKEN_MODEL": None,
}


# DRF and JWT configuration

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "accounts.authentication.CookieOrHeaderJWTAuthentication",
    ),
    "DEFAULT_THROTTLE_CLASSES": (
        "accounts.throttles.AuthSecurityThrottle",
        "accounts.throttles.ApiMutationThrottle",
        "accounts.throttles.GameCommandThrottle",
        "accounts.throttles.RegistrationCommandThrottle",
    ),
    "EXCEPTION_HANDLER": "api.exception_handler.api_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_RATES": {
        "auth_security": "10/min",
        "api_mutation": "120/min",
        "game_command": "60/min",
        "registration_command": "30/min",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=8),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

JWT_ACCESS_COOKIE = "access_token"
JWT_REFRESH_COOKIE = "refresh_token"
JWT_COOKIE_SECURE = True
JWT_COOKIE_SAMESITE = "Lax"

SPECTACULAR_SETTINGS = {
    "TITLE": "Dice Tournament API",
    "DESCRIPTION": "Authoritative REST contract for Dice Tournament.",
    "VERSION": "1.0.0",
}


# Redis and Channels

REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [REDIS_URL]},
    },
}


# Celery

CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL",
    "redis://127.0.0.1:6379/1",
)

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_TASK_IGNORE_RESULT = True

CELERY_TIMEZONE = "UTC"
CELERY_TASK_DEFAULT_QUEUE = "maintenance"
CELERY_TASK_CREATE_MISSING_QUEUES = False

CELERY_TASK_QUEUES = (
    Queue("notifications", exchange="notifications", routing_key="notifications"),
    Queue("maintenance", exchange="maintenance", routing_key="maintenance"),
)

CELERY_TASK_ROUTES = {
    "tournaments.tasks.notifications.send_tournament_invitation": {
        "queue": "notifications",
    },
    "tournaments.tasks.maintenance.cleanup_expired_idempotency_records": {
        "queue": "maintenance",
    },
    "tournaments.tasks.maintenance.flush_expired_tokens": {
        "queue": "maintenance",
    },
}

CELERY_BEAT_SCHEDULE = {
    "cleanup-expired-idempotency-records": {
        "task": ("tournaments.tasks.maintenance.cleanup_expired_idempotency_records"),
        "schedule": crontab(hour=2, minute=0),
        "options": {"queue": "maintenance"},
    },
    "flush-expired-jwt-tokens": {
        "task": "tournaments.tasks.maintenance.flush_expired_tokens",
        "schedule": crontab(hour=2, minute=15),
        "options": {"queue": "maintenance"},
    },
}

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


# Idempotency

try:
    IDEMPOTENCY_RETENTION_HOURS = int(os.getenv("IDEMPOTENCY_RETENTION_HOURS", "24"))
except ValueError as exc:
    raise ImproperlyConfigured(
        "IDEMPOTENCY_RETENTION_HOURS must be an integer."
    ) from exc

if IDEMPOTENCY_RETENTION_HOURS <= 0:
    raise ImproperlyConfigured("IDEMPOTENCY_RETENTION_HOURS must be greater than zero.")
