# Generated by Django 6.1 on 2026-09-02 16:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import tournaments.models.tournament


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("registration", "Registration"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "registration_mode",
                    models.CharField(
                        choices=[
                            ("organizer_only", "Organizer only"),
                            ("open", "Open"),
                        ],
                        default="organizer_only",
                        max_length=20,
                    ),
                ),
                (
                    "min_participants",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(128),
                        ]
                    ),
                ),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                ("registration_closed_at", models.DateTimeField(blank=True, null=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "timezone",
                    models.CharField(
                        max_length=64,
                        validators=[
                            tournaments.models.tournament.validate_iana_timezone
                        ],
                    ),
                ),
                (
                    "group_rounds",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(2)],
                    ),
                ),
                (
                    "table_size",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                (
                    "decision_time_limit",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unlimited"),
                            (30, "30 seconds"),
                            (60, "60 seconds"),
                            (90, "90 seconds"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "event_mode",
                    models.CharField(
                        choices=[("in_person", "In person"), ("remote", "Remote")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TournamentOrganizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_organizers",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_organizer_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tournament", "user"),
                        name="unique_tournament_organizer",
                    )
                ],
            },
        ),
    ]
