# Generated by Django 6.1 on 2026-09-02 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="organizers",
            field=models.ManyToManyField(
                related_name="organized_tournaments",
                through="tournaments.TournamentOrganizer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
