# Generated by Django 6.1 on 2026-09-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_tournament_organizers"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="poker_scoring_variant",
            field=models.CharField(
                choices=[
                    ("a", "Variant A — descending"),
                    ("b", "Variant B — ascending"),
                ],
                default="a",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
