# Generated by Django 6.1 on 2026-09-02 19:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("tournaments", "0003_tournament_poker_scoring_variant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name_snapshot", models.CharField(max_length=301)),
                ("display_name_snapshot", models.CharField(max_length=150)),
                ("nickname_snapshot", models.CharField(blank=True, max_length=50)),
                ("team_label", models.CharField(blank=True, max_length=150)),
                (
                    "starting_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "seeding",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("active", "Active"),
                            ("withdrawn", "Withdrawn"),
                            ("eliminated", "Eliminated"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                ("total_score", models.IntegerField(default=0)),
                (
                    "player_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tournament_participations",
                        to="accounts.playerprofile",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_participants",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawn_tournament_participants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tournament",
            name="participants",
            field=models.ManyToManyField(
                related_name="tournaments",
                through="tournaments.TournamentParticipant",
                to="accounts.playerprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentparticipant",
            constraint=models.UniqueConstraint(
                fields=("tournament", "player_profile"),
                name="unique_tournament_participant",
            ),
        ),
    ]
