# Generated by Django 6.1 on 2026-09-06 13:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0005_round"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_number",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("allocation_seed", models.BigIntegerField()),
                ("allocation_cost", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="tournaments.round",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turn_order",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("raw_score", models.IntegerField(default=0)),
                ("school_balance", models.IntegerField(default=0)),
                ("figure_points", models.IntegerField(default=0)),
                ("bonus_points", models.IntegerField(default=0)),
                ("final_score", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_participants",
                        to="tournaments.game",
                    ),
                ),
                (
                    "tournament_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="game_participations",
                        to="tournaments.tournamentparticipant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Turn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("held_die_1", models.BooleanField(default=False)),
                ("held_die_2", models.BooleanField(default=False)),
                ("held_die_3", models.BooleanField(default=False)),
                ("held_die_4", models.BooleanField(default=False)),
                ("held_die_5", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="tournaments.gameparticipant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScoreEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ones", "1"),
                            ("twos", "2"),
                            ("threes", "3"),
                            ("fours", "4"),
                            ("fives", "5"),
                            ("sixes", "6"),
                            ("pair", "Pair"),
                            ("two_pairs", "Two Pairs"),
                            ("triple", "Triple"),
                            ("quad", "Quad"),
                            ("full", "Full"),
                            ("even", "Even"),
                            ("odd", "Odd"),
                            ("small_straight", "Small Straight"),
                            ("large_straight", "Large Straight"),
                            ("gap", "Gap"),
                            ("chance", "Chance"),
                            ("poker", "Poker"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "result_kind",
                    models.CharField(
                        choices=[
                            ("points", "Points"),
                            ("school_balance", "School balance"),
                            ("strike_off", "Strike-off"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_entries",
                        to="tournaments.gameparticipant",
                    ),
                ),
                (
                    "turn",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_entry",
                        to="tournaments.turn",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Roll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_number", models.PositiveSmallIntegerField()),
                ("die_1", models.PositiveSmallIntegerField()),
                ("die_2", models.PositiveSmallIntegerField()),
                ("die_3", models.PositiveSmallIntegerField()),
                ("die_4", models.PositiveSmallIntegerField()),
                ("die_5", models.PositiveSmallIntegerField()),
                ("held_die_1", models.BooleanField(default=False)),
                ("held_die_2", models.BooleanField(default=False)),
                ("held_die_3", models.BooleanField(default=False)),
                ("held_die_4", models.BooleanField(default=False)),
                ("held_die_5", models.BooleanField(default=False)),
                ("rolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rolls",
                        to="tournaments.turn",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                fields=("round", "display_number"),
                name="unique_game_display_number_per_round",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameparticipant",
            constraint=models.UniqueConstraint(
                fields=("game", "tournament_participant"),
                name="unique_participant_per_game",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameparticipant",
            constraint=models.UniqueConstraint(
                fields=("game", "turn_order"), name="unique_turn_order_per_game"
            ),
        ),
        migrations.AddConstraint(
            model_name="turn",
            constraint=models.UniqueConstraint(
                fields=("game_participant", "number"),
                name="unique_turn_number_per_game_participant",
            ),
        ),
        migrations.AddConstraint(
            model_name="scoreentry",
            constraint=models.UniqueConstraint(
                fields=("game_participant", "category"),
                name="unique_score_category_per_game_participant",
            ),
        ),
        migrations.AddConstraint(
            model_name="scoreentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("result_kind", "strike_off"), ("value__isnull", True)),
                    models.Q(
                        models.Q(("result_kind", "strike_off"), _negated=True),
                        ("value__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="score_entry_value_matches_result_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="roll",
            constraint=models.CheckConstraint(
                condition=models.Q(("roll_number__gte", 1), ("roll_number__lte", 3)),
                name="roll_number_between_1_and_3",
            ),
        ),
        migrations.AddConstraint(
            model_name="roll",
            constraint=models.CheckConstraint(
                condition=models.Q(("die_1__gte", 1), ("die_1__lte", 6)),
                name="roll_die_1_between_1_and_6",
            ),
        ),
        migrations.AddConstraint(
            model_name="roll",
            constraint=models.CheckConstraint(
                condition=models.Q(("die_2__gte", 1), ("die_2__lte", 6)),
                name="roll_die_2_between_1_and_6",
            ),
        ),
        migrations.AddConstraint(
            model_name="roll",
            constraint=models.CheckConstraint(
                condition=models.Q(("die_3__gte", 1), ("die_3__lte", 6)),
                name="roll_die_3_between_1_and_6",
            ),
        ),
        migrations.AddConstraint(
            model_name="roll",
            constraint=models.CheckConstraint(
                condition=models.Q(("die_4__gte", 1), ("die_4__lte", 6)),
                name="roll_die_4_between_1_and_6",
            ),
        ),
        migrations.AddConstraint(
            model_name="roll",
            constraint=models.CheckConstraint(
                condition=models.Q(("die_5__gte", 1), ("die_5__lte", 6)),
                name="roll_die_5_between_1_and_6",
            ),
        ),
        migrations.AddConstraint(
            model_name="roll",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("roll_number", 1), _negated=True),
                    models.Q(
                        ("held_die_1", False),
                        ("held_die_2", False),
                        ("held_die_3", False),
                        ("held_die_4", False),
                        ("held_die_5", False),
                    ),
                    _connector="OR",
                ),
                name="first_roll_has_no_held_dice",
            ),
        ),
        migrations.AddConstraint(
            model_name="roll",
            constraint=models.UniqueConstraint(
                fields=("turn", "roll_number"), name="unique_roll_number_per_turn"
            ),
        ),
    ]
