# Generated by Django 6.1 on 2026-09-07 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0007_idempotencyrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="type",
            field=models.CharField(
                choices=[("group", "Group"), ("overtime", "Overtime")],
                default="group",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TieBreakDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_participant_ids", models.JSONField()),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tie_break_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tie_break_decisions",
                        to="tournaments.round",
                    ),
                ),
                (
                    "selected_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tie_break_decisions",
                        to="tournaments.tournamentparticipant",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tie_break_decisions",
                        to="tournaments.tournament",
                    ),
                ),
            ],
        ),
    ]
