# Generated by Django 6.1 on 2026-09-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0008_alter_round_type_tiebreakdecision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentparticipant",
            name="team_label",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
