# Generated by Django 6.1 on 2026-09-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0009_alter_tournamentparticipant_team_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="state_version",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
