# Generated by Django 6.1 on 2026-09-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0010_game_state_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentparticipant",
            name="active_connection_channel",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tournamentparticipant",
            name="connection_status",
            field=models.CharField(
                choices=[
                    ("connected", "Connected"),
                    ("reconnecting", "Reconnecting"),
                    ("disconnected", "Disconnected"),
                ],
                default="disconnected",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tournamentparticipant",
            name="disconnected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="turn",
            name="action_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
