# Generated by Django 6.1 on 2026-09-16 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tournaments",
            "0011_tournamentparticipant_active_connection_channel_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tiebreakdecision",
            constraint=models.UniqueConstraint(
                fields=("round",), name="unique_tie_break_decision_per_round"
            ),
        ),
    ]
