# Generated by Django 6.1 on 2026-09-07 20:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionFamily",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("absolute_expires_at", models.DateTimeField()),
                ("last_activity_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_families",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "revoked_at"],
                        name="accounts_se_user_id_0ce40a_idx",
                    ),
                    models.Index(
                        fields=["absolute_expires_at"],
                        name="accounts_se_absolut_e42558_idx",
                    ),
                ],
            },
        ),
    ]
